# .github/workflows/main.yml
name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Pylint
      run: pip install pylint

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Run linting
      run: |
        pylint hello.py

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
   
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t mkashupp/hello-docker:latest .
        docker push mkashupp/hello-docker:latest