# .github/workflows/main.yml
name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Pylint
      run: pip install pylint

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Run linting
      run: |
        pylint hello.py

    - name: Build Docker image
      run: |
        docker build -t mkashupp/hello-docker .
        docker push mkashupp/hello-docker